### ISSUE TITLE
Reunion 23/12/2021

### ISSUE THREAD

**Issue by juanlod** [juanlod/P1.1-PracticaVideoxogoComun#16]

**Comment by juanlod** [comment]
Se reasignan las tareas dependiendo de la capacidad de trabajo de los integrantes del equipo

Miguel hace investigación de assets y selecciona los mejores para el desarrollo del videojuego.
Se determina que los assets de Sunny Land nos proporciona la gran mayoría de funcionalidades de movimiento.

Se aprueba el uso de los assets para facilitar el desarrollo y los tiempos.

**Comment by borjafdzan** [comment]
Hola puedes crear una issue para que la camara siga al jugador y otro para que el jugador haga respawn cuando muera?

**Comment by juanlod** [comment]
Si, las acabo de crear borja.
