### ISSUE TITLE
Asignación de movemento lateral dereito ó personaxe

### ISSUE THREAD

**Issue by juanlod** [juanlod/P1.1-PracticaVideoxogoComun#2]
O personaxe débese poder mover o lado esquerdo premendo  a flecha dereita do  teclado

**Comment by borjafdzan** [comment]
Hola, ya esta implementada la funcionalidad de la issue #1 y la issue #2 @9RACHA ya esta listo para testear.

**Comment by borjafdzan** [comment]
esta en al branch desarrollo

**Comment by juanlod** [comment]
Gracias borja

**Comment by juanlod** [comment]
Ahora a tarde creovos as tareas de testing que onte salín muy tarde (11h) porque houbo bastantes incidencias e os traballadores non podía currar.

**Comment by 9RACHA** [comment]
Testeada la issue #1 y #2 de @borjafdzan, sin errores.
