### ISSUE TITLE
Asignación de movemento de salto ó personaxe

### ISSUE THREAD

**Issue by juanlod** [juanlod/P1.1-PracticaVideoxogoComun#3]
O personaxe debe poder saltar o premer a tecla de barra espaciadora

**Comment by borjafdzan** [comment]
Hola, ya esta la funcionalidad de salto para el pesonaje de la issue #3, esta en la rama de desarrollo-salto @9RACHA , en principio esta lista para testear.

**Comment by juanlod** [comment]
Gracias borja
